### ISSUE TITLE
quiz.php: Specify order of questions

### ISSUE THREAD

**Issue by jonschipp** [jonschipp/quiz#3]
Option for question order randomizing, sequential, reverse, etc.

**Comment by mikedowney01** [comment]
The default is to randomize. I will have an option tonight to specify sequential and revers.

**Comment by mikedowney01** [comment]
-s option has been added to specify sequential (-s seq) or reverse (-s rev) sorting.
Also, the -q option works with this as well. 
For instance, to generate the first 5 questions "./quiz.php -f path/to/quiz -s seq -q 5"
