### ISSUE TITLE
quiz.php: separate code or examples blocks from questions

### ISSUE THREAD

**Issue by jonschipp** [jonschipp/quiz#5]
In the question, if there's text in the single or double quotes assume it's a code, command, or config file example and format it different from the rest of the question. Also, allow escape codes (e.g. \n,\t) in quotes so code examples can expand multiple lines.

e.g. 

In the following output of sshd_config "PermitTunnel no" what does this option do?,x,y,z

```
In the following output of sshd_config

"PermitTunnel no"

what does this option do?
```

**Comment by jonathonklem** [comment]
It's going to be `impossible` to do the second part about outputting formatted with quotes.

**Comment by jonathonklem** [comment]
Mike and I fixed this together

**Comment by jonschipp** [comment]
You guys rule, thanks!
