### ISSUE TITLE
quiz.php: add option to show answer after question

### ISSUE THREAD

**Issue by jonschipp** [jonschipp/quiz#6]

**Comment by mikedowney01** [comment]
I think that's a great idea! Maybe even show a "Correct!" or "Incorrect." in green and read respectively.

**Comment by mikedowney01** [comment]
Should this be an option or default? I currently have it as default, showing "Correct!" or "Incorrect. The correct answer is "answer". Let me know if this works and I'll close.

**Comment by mikedowney01** [comment]
Closing issue. Another can be opened to make this feature optional (if desired).
